name: PowerShell Lint with PSScriptAnalyzer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PowerShell
        uses: actions/setup-powershell@v2

      - name: Install PSScriptAnalyzer
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        shell: pwsh

      - name: Run PSScriptAnalyzer
        run: |
          Invoke-ScriptAnalyzer -Path .\Get-EntraSignInLogs.ps1 -Recurse -Severity Warning, Error
        shell: pwsh
